name: geo_json_painter
description: Library for parsing the GeoJson format based on the RFC 7946 specification and displaying GeoJson on canvas
version: 0.3.0
homepage: https://github.com/lesleysin/geo_json_painter

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

